/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BookedSeat = {
  _type: "bookedSeat";
  seatNumber?: string;
  passengerName?: string;
  fee?: number;
};

export type FlightReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "flight";
};

export type BookingLeg = {
  _type: "bookingLeg";
  flight?: FlightReference;
  cabinClass?: "economy" | "business" | "first";
  seats?: Array<
    {
      _key: string;
    } & BookedSeat
  >;
};

export type Fare = {
  _type: "fare";
  cabinClass?: "economy" | "business" | "first";
  basePrice?: number;
  seatFee?: number;
  exitRowSeatFee?: number;
  currency?: string;
};

export type CabinSection = {
  _type: "cabinSection";
  cabinClass?: "economy" | "business" | "first";
  startRow?: number;
  endRow?: number;
  columnLayout?: string;
  exitRows?: Array<number>;
};

export type SupportArticle = {
  _id: string;
  _type: "supportArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  slug?: Slug;
  category?: "baggage" | "checkin" | "changes" | "seats" | "payments" | "pro";
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Booking = {
  _id: string;
  _type: "booking";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pnr?: string;
  clerkUserId?: string;
  contactName?: string;
  contactEmail?: string;
  tripType?: "oneway" | "roundtrip";
  outbound?: BookingLeg;
  inbound?: BookingLeg;
  passengers?: Array<{
    fullName?: string;
    dateOfBirth?: string;
    _type: "passenger";
    _key: string;
  }>;
  fareBreakdown?: {
    baseFare?: number;
    seatFees?: number;
    taxes?: number;
    total?: number;
    currency?: string;
  };
  proSeatFeesWaived?: boolean;
  status?: "pending" | "confirmed" | "cancelled";
  payment?: {
    method?: string;
    last4?: string;
    transactionId?: string;
    paidAt?: string;
  };
  bookedVia?: "checkout" | "concierge";
};

export type AirlineReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "airline";
};

export type AircraftReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aircraft";
};

export type AirportReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "airport";
};

export type Flight = {
  _id: string;
  _type: "flight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  flightNumber?: string;
  airline?: AirlineReference;
  aircraft?: AircraftReference;
  origin?: AirportReference;
  destination?: AirportReference;
  departureTime?: string;
  arrivalTime?: string;
  durationMinutes?: number;
  fares?: Array<
    {
      _key: string;
    } & Fare
  >;
  status?: "scheduled" | "cancelled";
};

export type Aircraft = {
  _id: string;
  _type: "aircraft";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  model?: string;
  registration?: string;
  seatLayout?: Array<
    {
      _key: string;
    } & CabinSection
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Airline = {
  _id: string;
  _type: "airline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  code?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Airport = {
  _id: string;
  _type: "airport";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  code?: string;
  name?: string;
  city?: string;
  country?: string;
  timezone?: string;
};

export type SanityAgentContextConversation = {
  _id: string;
  _type: "sanity.agentContextConversation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  agentId?: string;
  threadId?: string;
  messages?: Array<{
    role?: "user" | "assistant" | "system" | "tool";
    content?: string;
    toolName?: string;
    toolType?: "call" | "result";
    _type: "conversationMessage";
    _key: string;
  }>;
  startedAt?: string;
  messagesUpdatedAt?: string;
  modelProvider?: string;
  modelId?: string;
  tokenUsage?: {
    inputTokens?: number;
    outputTokens?: number;
    totalTokens?: number;
  };
  coreMetrics?: {
    successScore?: number;
    sentiment?: "positive" | "neutral" | "negative";
    contentGaps?: Array<string>;
  };
  classifiedAt?: string;
  classificationError?: string;
};

export type SanityAgentContext = {
  _id: string;
  _type: "sanity.agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  version?: string;
  name?: string;
  slug?: Slug;
  groqFilter?: string;
  instructions?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BookedSeat
  | FlightReference
  | BookingLeg
  | Fare
  | CabinSection
  | SupportArticle
  | Slug
  | Booking
  | AirlineReference
  | AircraftReference
  | AirportReference
  | Flight
  | Aircraft
  | SanityImageAssetReference
  | Airline
  | SanityImageCrop
  | SanityImageHotspot
  | Airport
  | SanityAgentContextConversation
  | SanityAgentContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: AIRPORTS_QUERY
// Query: *[_type == "airport"] | order(code asc) {_id, code, name, city, country}
export type AIRPORTS_QUERY_RESULT = Array<{
  _id: string;
  code: string | null;
  name: string | null;
  city: string | null;
  country: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SEARCH_FLIGHTS_QUERY
// Query: *[    _type == "flight" &&    status == "scheduled" &&    origin->code == $originCode &&    destination->code == $destinationCode &&    departureTime >= $dayStart &&    departureTime < $dayEnd &&    count(fares[cabinClass == $cabinClass]) > 0  ] | order(departureTime asc) {  _id,  flightNumber,  departureTime,  arrivalTime,  durationMinutes,  fares,  status,  airline->{_id, name, code},  aircraft->{_id, model, seatLayout},  origin->{_id, code, name, city, timezone},  destination->{_id, code, name, city, timezone},}
export type SEARCH_FLIGHTS_QUERY_RESULT = Array<{
  _id: string;
  flightNumber: string | null;
  departureTime: string | null;
  arrivalTime: string | null;
  durationMinutes: number | null;
  fares: Array<
    {
      _key: string;
    } & Fare
  > | null;
  status: "cancelled" | "scheduled" | null;
  airline: {
    _id: string;
    name: string | null;
    code: string | null;
  } | null;
  aircraft: {
    _id: string;
    model: string | null;
    seatLayout: Array<
      {
        _key: string;
      } & CabinSection
    > | null;
  } | null;
  origin: {
    _id: string;
    code: string | null;
    name: string | null;
    city: string | null;
    timezone: string | null;
  } | null;
  destination: {
    _id: string;
    code: string | null;
    name: string | null;
    city: string | null;
    timezone: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: FLIGHT_BY_ID_QUERY
// Query: *[_type == "flight" && _id == $id][0] {  _id,  flightNumber,  departureTime,  arrivalTime,  durationMinutes,  fares,  status,  airline->{_id, name, code},  aircraft->{_id, model, seatLayout},  origin->{_id, code, name, city, timezone},  destination->{_id, code, name, city, timezone},}
export type FLIGHT_BY_ID_QUERY_RESULT = {
  _id: string;
  flightNumber: string | null;
  departureTime: string | null;
  arrivalTime: string | null;
  durationMinutes: number | null;
  fares: Array<
    {
      _key: string;
    } & Fare
  > | null;
  status: "cancelled" | "scheduled" | null;
  airline: {
    _id: string;
    name: string | null;
    code: string | null;
  } | null;
  aircraft: {
    _id: string;
    model: string | null;
    seatLayout: Array<
      {
        _key: string;
      } & CabinSection
    > | null;
  } | null;
  origin: {
    _id: string;
    code: string | null;
    name: string | null;
    city: string | null;
    timezone: string | null;
  } | null;
  destination: {
    _id: string;
    code: string | null;
    name: string | null;
    city: string | null;
    timezone: string | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: OCCUPIED_SEATS_QUERY
// Query: *[    _type == "booking" &&    status != "cancelled" &&    (outbound.flight._ref == $flightId || inbound.flight._ref == $flightId)  ]{    "seats": select(      outbound.flight._ref == $flightId => outbound.seats[].seatNumber,      inbound.flight._ref == $flightId => inbound.seats[].seatNumber,    )  }.seats[]
export type OCCUPIED_SEATS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: MY_BOOKINGS_QUERY
// Query: *[_type == "booking" && clerkUserId == $clerkUserId] | order(_createdAt desc) {    _id,    pnr,    tripType,    status,    fareBreakdown,    bookedVia,    _createdAt,    outbound{      cabinClass,      seats,      flight->{  _id,  flightNumber,  departureTime,  arrivalTime,  durationMinutes,  fares,  status,  airline->{_id, name, code},  aircraft->{_id, model, seatLayout},  origin->{_id, code, name, city, timezone},  destination->{_id, code, name, city, timezone},}    },    inbound{      cabinClass,      seats,      flight->{  _id,  flightNumber,  departureTime,  arrivalTime,  durationMinutes,  fares,  status,  airline->{_id, name, code},  aircraft->{_id, model, seatLayout},  origin->{_id, code, name, city, timezone},  destination->{_id, code, name, city, timezone},}    }  }
export type MY_BOOKINGS_QUERY_RESULT = Array<{
  _id: string;
  pnr: string | null;
  tripType: "oneway" | "roundtrip" | null;
  status: "cancelled" | "confirmed" | "pending" | null;
  fareBreakdown: {
    baseFare?: number;
    seatFees?: number;
    taxes?: number;
    total?: number;
    currency?: string;
  } | null;
  bookedVia: "checkout" | "concierge" | null;
  _createdAt: string;
  outbound: {
    cabinClass: "business" | "economy" | "first" | null;
    seats: Array<
      {
        _key: string;
      } & BookedSeat
    > | null;
    flight: {
      _id: string;
      flightNumber: string | null;
      departureTime: string | null;
      arrivalTime: string | null;
      durationMinutes: number | null;
      fares: Array<
        {
          _key: string;
        } & Fare
      > | null;
      status: "cancelled" | "scheduled" | null;
      airline: {
        _id: string;
        name: string | null;
        code: string | null;
      } | null;
      aircraft: {
        _id: string;
        model: string | null;
        seatLayout: Array<
          {
            _key: string;
          } & CabinSection
        > | null;
      } | null;
      origin: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
      destination: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
    } | null;
  } | null;
  inbound: {
    cabinClass: "business" | "economy" | "first" | null;
    seats: Array<
      {
        _key: string;
      } & BookedSeat
    > | null;
    flight: {
      _id: string;
      flightNumber: string | null;
      departureTime: string | null;
      arrivalTime: string | null;
      durationMinutes: number | null;
      fares: Array<
        {
          _key: string;
        } & Fare
      > | null;
      status: "cancelled" | "scheduled" | null;
      airline: {
        _id: string;
        name: string | null;
        code: string | null;
      } | null;
      aircraft: {
        _id: string;
        model: string | null;
        seatLayout: Array<
          {
            _key: string;
          } & CabinSection
        > | null;
      } | null;
      origin: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
      destination: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: BOOKING_BY_PNR_QUERY
// Query: *[_type == "booking" && pnr == $pnr][0]{    _id,    pnr,    clerkUserId,    contactName,    contactEmail,    tripType,    status,    fareBreakdown,    proSeatFeesWaived,    payment,    passengers,    bookedVia,    outbound{      cabinClass,      seats,      flight->{  _id,  flightNumber,  departureTime,  arrivalTime,  durationMinutes,  fares,  status,  airline->{_id, name, code},  aircraft->{_id, model, seatLayout},  origin->{_id, code, name, city, timezone},  destination->{_id, code, name, city, timezone},}    },    inbound{      cabinClass,      seats,      flight->{  _id,  flightNumber,  departureTime,  arrivalTime,  durationMinutes,  fares,  status,  airline->{_id, name, code},  aircraft->{_id, model, seatLayout},  origin->{_id, code, name, city, timezone},  destination->{_id, code, name, city, timezone},}    }  }
export type BOOKING_BY_PNR_QUERY_RESULT = {
  _id: string;
  pnr: string | null;
  clerkUserId: string | null;
  contactName: string | null;
  contactEmail: string | null;
  tripType: "oneway" | "roundtrip" | null;
  status: "cancelled" | "confirmed" | "pending" | null;
  fareBreakdown: {
    baseFare?: number;
    seatFees?: number;
    taxes?: number;
    total?: number;
    currency?: string;
  } | null;
  proSeatFeesWaived: boolean | null;
  payment: {
    method?: string;
    last4?: string;
    transactionId?: string;
    paidAt?: string;
  } | null;
  passengers: Array<{
    fullName?: string;
    dateOfBirth?: string;
    _type: "passenger";
    _key: string;
  }> | null;
  bookedVia: "checkout" | "concierge" | null;
  outbound: {
    cabinClass: "business" | "economy" | "first" | null;
    seats: Array<
      {
        _key: string;
      } & BookedSeat
    > | null;
    flight: {
      _id: string;
      flightNumber: string | null;
      departureTime: string | null;
      arrivalTime: string | null;
      durationMinutes: number | null;
      fares: Array<
        {
          _key: string;
        } & Fare
      > | null;
      status: "cancelled" | "scheduled" | null;
      airline: {
        _id: string;
        name: string | null;
        code: string | null;
      } | null;
      aircraft: {
        _id: string;
        model: string | null;
        seatLayout: Array<
          {
            _key: string;
          } & CabinSection
        > | null;
      } | null;
      origin: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
      destination: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
    } | null;
  } | null;
  inbound: {
    cabinClass: "business" | "economy" | "first" | null;
    seats: Array<
      {
        _key: string;
      } & BookedSeat
    > | null;
    flight: {
      _id: string;
      flightNumber: string | null;
      departureTime: string | null;
      arrivalTime: string | null;
      durationMinutes: number | null;
      fares: Array<
        {
          _key: string;
        } & Fare
      > | null;
      status: "cancelled" | "scheduled" | null;
      airline: {
        _id: string;
        name: string | null;
        code: string | null;
      } | null;
      aircraft: {
        _id: string;
        model: string | null;
        seatLayout: Array<
          {
            _key: string;
          } & CabinSection
        > | null;
      } | null;
      origin: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
      destination: {
        _id: string;
        code: string | null;
        name: string | null;
        city: string | null;
        timezone: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: SUPPORT_ARTICLES_QUERY
// Query: *[_type == "supportArticle"] | order(category asc) {_id, question, category, answer}
export type SUPPORT_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  question: string | null;
  category:
    "baggage" | "changes" | "checkin" | "payments" | "pro" | "seats" | null;
  answer: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "airport"] | order(code asc) {_id, code, name, city, country}': AIRPORTS_QUERY_RESULT;
    '*[\n    _type == "flight" &&\n    status == "scheduled" &&\n    origin->code == $originCode &&\n    destination->code == $destinationCode &&\n    departureTime >= $dayStart &&\n    departureTime < $dayEnd &&\n    count(fares[cabinClass == $cabinClass]) > 0\n  ] | order(departureTime asc) {\n  _id,\n  flightNumber,\n  departureTime,\n  arrivalTime,\n  durationMinutes,\n  fares,\n  status,\n  airline->{_id, name, code},\n  aircraft->{_id, model, seatLayout},\n  origin->{_id, code, name, city, timezone},\n  destination->{_id, code, name, city, timezone},\n}': SEARCH_FLIGHTS_QUERY_RESULT;
    '*[_type == "flight" && _id == $id][0] {\n  _id,\n  flightNumber,\n  departureTime,\n  arrivalTime,\n  durationMinutes,\n  fares,\n  status,\n  airline->{_id, name, code},\n  aircraft->{_id, model, seatLayout},\n  origin->{_id, code, name, city, timezone},\n  destination->{_id, code, name, city, timezone},\n}': FLIGHT_BY_ID_QUERY_RESULT;
    '*[\n    _type == "booking" &&\n    status != "cancelled" &&\n    (outbound.flight._ref == $flightId || inbound.flight._ref == $flightId)\n  ]{\n    "seats": select(\n      outbound.flight._ref == $flightId => outbound.seats[].seatNumber,\n      inbound.flight._ref == $flightId => inbound.seats[].seatNumber,\n    )\n  }.seats[]': OCCUPIED_SEATS_QUERY_RESULT;
    '*[_type == "booking" && clerkUserId == $clerkUserId] | order(_createdAt desc) {\n    _id,\n    pnr,\n    tripType,\n    status,\n    fareBreakdown,\n    bookedVia,\n    _createdAt,\n    outbound{\n      cabinClass,\n      seats,\n      flight->{\n  _id,\n  flightNumber,\n  departureTime,\n  arrivalTime,\n  durationMinutes,\n  fares,\n  status,\n  airline->{_id, name, code},\n  aircraft->{_id, model, seatLayout},\n  origin->{_id, code, name, city, timezone},\n  destination->{_id, code, name, city, timezone},\n}\n    },\n    inbound{\n      cabinClass,\n      seats,\n      flight->{\n  _id,\n  flightNumber,\n  departureTime,\n  arrivalTime,\n  durationMinutes,\n  fares,\n  status,\n  airline->{_id, name, code},\n  aircraft->{_id, model, seatLayout},\n  origin->{_id, code, name, city, timezone},\n  destination->{_id, code, name, city, timezone},\n}\n    }\n  }': MY_BOOKINGS_QUERY_RESULT;
    '*[_type == "booking" && pnr == $pnr][0]{\n    _id,\n    pnr,\n    clerkUserId,\n    contactName,\n    contactEmail,\n    tripType,\n    status,\n    fareBreakdown,\n    proSeatFeesWaived,\n    payment,\n    passengers,\n    bookedVia,\n    outbound{\n      cabinClass,\n      seats,\n      flight->{\n  _id,\n  flightNumber,\n  departureTime,\n  arrivalTime,\n  durationMinutes,\n  fares,\n  status,\n  airline->{_id, name, code},\n  aircraft->{_id, model, seatLayout},\n  origin->{_id, code, name, city, timezone},\n  destination->{_id, code, name, city, timezone},\n}\n    },\n    inbound{\n      cabinClass,\n      seats,\n      flight->{\n  _id,\n  flightNumber,\n  departureTime,\n  arrivalTime,\n  durationMinutes,\n  fares,\n  status,\n  airline->{_id, name, code},\n  aircraft->{_id, model, seatLayout},\n  origin->{_id, code, name, city, timezone},\n  destination->{_id, code, name, city, timezone},\n}\n    }\n  }': BOOKING_BY_PNR_QUERY_RESULT;
    '*[_type == "supportArticle"] | order(category asc) {_id, question, category, answer}': SUPPORT_ARTICLES_QUERY_RESULT;
  }
}
